
name: 'ROOT Docs Main'

on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 12 * * *'
      
jobs:
  run_nightlies:
    uses: root-project/root/.github/workflows/root-docs-ci.yml@master
    secrets: inherit
